// Exercise Information Database
// Contains instructions, form cues, and muscles for common exercises

export interface ExerciseInfo {
    name: string;
    muscles: string[];
    equipment: string;
    difficulty: 'beginner' | 'intermediate' | 'advanced';
    instructions: string[];
    formCues: string[];
    commonMistakes: string[];
    icon: string;
    imageKey?: string; // Key for exercise diagram image
}

export const EXERCISE_DATABASE: Record<string, ExerciseInfo> = {
    // ============ CHEST ============
    'Bench Press': {
        name: 'Bench Press',
        muscles: ['Chest', 'Triceps', 'Front Delts'],
        equipment: 'Barbell, Bench',
        difficulty: 'intermediate',
        instructions: [
            'Lie flat on the bench with feet firmly planted',
            'Grip the bar slightly wider than shoulder-width',
            'Unrack and position bar over mid-chest',
            'Lower the bar with control to nipple line',
            'Press back up to lockout',
        ],
        formCues: ['Keep shoulders retracted', 'Maintain slight arch', 'Drive feet into floor', 'Squeeze chest at top'],
        commonMistakes: ['Bouncing off chest', 'Flaring elbows too wide', 'Lifting hips off bench'],
        icon: '🏋️',
        imageKey: 'bench_press',
    },
    'Incline Bench Press': {
        name: 'Incline Bench Press',
        muscles: ['Upper Chest', 'Triceps', 'Front Delts'],
        equipment: 'Barbell, Incline Bench',
        difficulty: 'intermediate',
        instructions: ['Set bench to 30-45 degree incline', 'Grip bar slightly wider than shoulder-width', 'Lower to upper chest/collarbone area', 'Press up and slightly back'],
        formCues: ['Keep back against pad', 'Control the descent', 'Press in slight arc'],
        commonMistakes: ['Bench too steep', 'Pressing straight up'],
        icon: '📐',
    }, 
    'Decline Bench Press': {
        name: 'Decline Bench Press',
        muscles: ['Lower Chest', 'Triceps', 'Front Delts'],
        equipment: 'Barbell, Decline Bench',
        difficulty: 'intermediate',
        instructions: ['Secure legs under pads', 'Grip bar slightly wider than shoulders', 'Lower to lower chest', 'Press up to lockout'],
        formCues: ['Stay tight', 'Control the bar path', 'Don\'t let bar drift'],
        commonMistakes: ['Too steep decline', 'Losing tightness'],
        icon: '📉',
    },
    'Dumbbell Bench Press': {
        name: 'Dumbbell Bench Press',
        muscles: ['Chest', 'Triceps', 'Front Delts'],
        equipment: 'Dumbbells, Bench',
        difficulty: 'beginner',
        instructions: ['Sit on bench, dumbbells on thighs', 'Kick back and lie flat, pressing DBs up', 'Lower with elbows at 45 degrees', 'Press up, bringing DBs together at top'],
        formCues: ['Squeeze chest at top', 'Full stretch at bottom', 'Control the weight'],
        commonMistakes: ['Dropping too fast', 'Elbows flaring 90 degrees'],
        icon: '💪',
    },
    'Incline Dumbbell Press': {
        name: 'Incline Dumbbell Press',
        muscles: ['Upper Chest', 'Front Delts', 'Triceps'],
        equipment: 'Dumbbells, Incline Bench',
        difficulty: 'beginner',
        instructions: ['Set bench to 30-45 degrees', 'Press dumbbells up from shoulders', 'Lower with control to chest level', 'Press up bringing DBs together'],
        formCues: ['Shoulders back', 'Feel stretch at bottom', 'Squeeze at top'],
        commonMistakes: ['Bench too steep', 'No pause at bottom'],
        icon: '📐',
    },
    'Dumbbell Fly': {
        name: 'Dumbbell Fly',
        muscles: ['Chest', 'Front Delts'],
        equipment: 'Dumbbells, Bench',
        difficulty: 'beginner',
        instructions: ['Lie flat with DBs extended above chest', 'Slight bend in elbows, fixed position', 'Lower DBs in wide arc to sides', 'Squeeze chest to bring back up'],
        formCues: ['Keep elbow angle fixed', 'Feel the stretch', 'Control the arc'],
        commonMistakes: ['Bending elbows too much', 'Going too heavy'],
        icon: '🦋',
    },
    'Cable Fly': {
        name: 'Cable Fly',
        muscles: ['Chest', 'Front Delts'],
        equipment: 'Cable Machine',
        difficulty: 'beginner',
        instructions: ['Stand between cable stations', 'Grab handles with slight elbow bend', 'Bring hands together in front', 'Squeeze and return with control'],
        formCues: ['Lean slightly forward', 'Squeeze at center', 'Constant tension'],
        commonMistakes: ['Too much arm movement', 'Standing too upright'],
        icon: '🔗',
    },
    'Push Ups': {
        name: 'Push Ups',
        muscles: ['Chest', 'Triceps', 'Core'],
        equipment: 'Bodyweight',
        difficulty: 'beginner',
        instructions: ['Start in plank position, hands shoulder-width', 'Keep body in straight line from head to heels', 'Lower chest to ground with control', 'Push back up to full extension'],
        formCues: ['Keep core tight', 'Elbows at 45 degrees', 'Full range of motion'],
        commonMistakes: ['Hips sagging', 'Not going low enough', 'Flared elbows'],
        icon: '🤸',
    },
    'Chest Dips': {
        name: 'Chest Dips',
        muscles: ['Lower Chest', 'Triceps', 'Front Delts'],
        equipment: 'Dip Bars',
        difficulty: 'intermediate',
        instructions: ['Grip bars and lift yourself up', 'Lean forward about 30 degrees', 'Lower until upper arms parallel to floor', 'Push back up'],
        formCues: ['Keep forward lean', 'Elbows slightly flared', 'Control the descent'],
        commonMistakes: ['Staying too upright', 'Going too deep'],
        icon: '⬇️',
    },

    // ============ BACK ============
    'Deadlift': {
        name: 'Deadlift',
        muscles: ['Lower Back', 'Glutes', 'Hamstrings', 'Traps'],
        equipment: 'Barbell',
        difficulty: 'advanced',
        instructions: ['Stand with feet hip-width, bar over mid-foot', 'Hinge at hips, grip bar just outside knees', 'Flatten back, brace core hard', 'Drive through legs while keeping bar close', 'Stand tall, squeeze glutes at top'],
        formCues: ['Bar stays close to body', 'Push floor away', 'Shoulders over bar at start', 'Hips and shoulders rise together'],
        commonMistakes: ['Rounding lower back', 'Bar drifting forward', 'Jerking off floor'],
        icon: '🏋️',
        imageKey: 'deadlift',
    },
    'Sumo Deadlift': {
        name: 'Sumo Deadlift',
        muscles: ['Quads', 'Glutes', 'Lower Back', 'Hamstrings'],
        equipment: 'Barbell',
        difficulty: 'advanced',
        instructions: ['Wide stance, toes pointed out', 'Grip bar inside knees', 'Push knees out, chest up', 'Drive through legs to stand'],
        formCues: ['Knees track over toes', 'Chest stays up', 'Push floor apart'],
        commonMistakes: ['Knees caving', 'Hips shooting up first'],
        icon: '🦵',
    },
    'Barbell Row': {
        name: 'Barbell Row',
        muscles: ['Lats', 'Upper Back', 'Biceps', 'Rear Delts'],
        equipment: 'Barbell',
        difficulty: 'intermediate',
        instructions: ['Hinge forward to 45-degree torso angle', 'Grip bar slightly wider than shoulder-width', 'Pull bar to lower chest/upper abs', 'Squeeze shoulder blades together', 'Lower with control'],
        formCues: ['Lead with elbows', 'Keep core braced', 'Squeeze at top for 1 second'],
        commonMistakes: ['Using too much momentum', 'Standing too upright', 'Not squeezing at top'],
        icon: '🚣',
        imageKey: 'barbell_row',
    },
    'Dumbbell Row': {
        name: 'Dumbbell Row',
        muscles: ['Lats', 'Upper Back', 'Biceps'],
        equipment: 'Dumbbell, Bench',
        difficulty: 'beginner',
        instructions: ['One knee and hand on bench', 'Row dumbbell to hip', 'Squeeze shoulder blade back', 'Lower with control'],
        formCues: ['Keep back flat', 'Pull to hip, not chest', 'Full stretch at bottom'],
        commonMistakes: ['Rotating torso', 'Pulling too high'],
        icon: '🚣',
    },
    'Pendlay Row': {
        name: 'Pendlay Row',
        muscles: ['Lats', 'Upper Back', 'Lower Back'],
        equipment: 'Barbell',
        difficulty: 'intermediate',
        instructions: ['Torso parallel to floor', 'Dead stop on floor each rep', 'Explosive pull to lower chest', 'Lower bar to floor'],
        formCues: ['Reset position each rep', 'Explosive pull', 'Flat back'],
        commonMistakes: ['Not resetting', 'Torso too upright'],
        icon: '💥',
    },
    'Pull Ups': {
        name: 'Pull Ups',
        muscles: ['Lats', 'Biceps', 'Upper Back'],
        equipment: 'Pull-up Bar',
        difficulty: 'intermediate',
        instructions: ['Hang with overhand grip, slightly wider than shoulders', 'Engage lats by depressing shoulders', 'Pull up until chin clears bar', 'Lower with control to full hang'],
        formCues: ['Initiate with lats, not arms', 'Drive elbows down', 'Chest up to bar'],
        commonMistakes: ['Kipping/swinging', 'Partial reps', 'Not engaging lats'],
        icon: '🦾',
        imageKey: 'pull_ups',
    },
    'Chin Ups': {
        name: 'Chin Ups',
        muscles: ['Biceps', 'Lats', 'Upper Back'],
        equipment: 'Pull-up Bar',
        difficulty: 'intermediate',
        instructions: ['Hang with underhand (supinated) grip', 'Shoulder-width grip', 'Pull up until chin over bar', 'Lower with control'],
        formCues: ['Squeeze biceps at top', 'Full hang at bottom', 'Control the negative'],
        commonMistakes: ['Swinging', 'Half reps'],
        icon: '💪',
    },
    'Lat Pulldown': {
        name: 'Lat Pulldown',
        muscles: ['Lats', 'Biceps', 'Upper Back'],
        equipment: 'Cable Machine',
        difficulty: 'beginner',
        instructions: ['Grip bar wider than shoulders', 'Sit with thighs secured under pads', 'Pull bar down to upper chest', 'Squeeze lats, then control back up'],
        formCues: ['Lead with elbows', 'Lean back slightly', 'Full stretch at top'],
        commonMistakes: ['Pulling behind neck', 'Leaning too far back', 'Using momentum'],
        icon: '⬇️',
    },
    'Seated Cable Row': {
        name: 'Seated Cable Row',
        muscles: ['Lats', 'Upper Back', 'Biceps'],
        equipment: 'Cable Machine',
        difficulty: 'beginner',
        instructions: ['Sit with feet on platform', 'Grab handle, arms extended', 'Pull to abs, squeeze shoulder blades', 'Return with control'],
        formCues: ['Chest up', 'Don\'t lean back too far', 'Squeeze at contraction'],
        commonMistakes: ['Excessive body swing', 'Rounding back'],
        icon: '🚣',
    },
    'T-Bar Row': {
        name: 'T-Bar Row',
        muscles: ['Lats', 'Upper Back', 'Lower Back'],
        equipment: 'T-Bar Machine or Landmine',
        difficulty: 'intermediate',
        instructions: ['Straddle bar, hinge forward', 'Grip handles or bar', 'Pull to chest', 'Lower with control'],
        formCues: ['Keep chest up', 'Squeeze at top', 'Stable lower back'],
        commonMistakes: ['Rounding back', 'Using momentum'],
        icon: '🏋️',
    },
    'Face Pulls': {
        name: 'Face Pulls',
        muscles: ['Rear Delts', 'Upper Back', 'Rotator Cuff'],
        equipment: 'Cable Machine, Rope',
        difficulty: 'beginner',
        instructions: ['Set cable at face height', 'Grip rope with palms facing down', 'Pull to face, separating rope', 'External rotate at end'],
        formCues: ['Lead with elbows high', 'Squeeze rear delts', 'External rotation at end'],
        commonMistakes: ['Pulling too low', 'No external rotation'],
        icon: '😊',
    },

    // ============ SHOULDERS ============
    'Overhead Press': {
        name: 'Overhead Press',
        muscles: ['Front Delts', 'Side Delts', 'Triceps'],
        equipment: 'Barbell',
        difficulty: 'intermediate',
        instructions: ['Stand with bar at shoulder height', 'Grip slightly wider than shoulders', 'Brace core, squeeze glutes', 'Press straight up, moving head back', 'Lock out overhead, head through'],
        formCues: ['Stay tight through core', 'Bar path is J-curve', 'Full lockout at top'],
        commonMistakes: ['Excessive back arch', 'Pressing forward', 'Loose core'],
        icon: '🙌',
        imageKey: 'overhead_press',
    },
    'Military Press': {
        name: 'Military Press',
        muscles: ['Front Delts', 'Side Delts', 'Triceps'],
        equipment: 'Barbell',
        difficulty: 'intermediate',
        instructions: ['Strict standing press', 'No leg drive', 'Bar starts at shoulders', 'Press to full lockout'],
        formCues: ['Squeeze glutes', 'Brace core hard', 'Straight bar path'],
        commonMistakes: ['Using leg drive', 'Leaning back'],
        icon: '🎖️',
    },
    'Dumbbell Shoulder Press': {
        name: 'Dumbbell Shoulder Press',
        muscles: ['Front Delts', 'Side Delts', 'Triceps'],
        equipment: 'Dumbbells',
        difficulty: 'beginner',
        instructions: ['Sit or stand with DBs at shoulders', 'Palms facing forward', 'Press up until arms extended', 'Lower with control'],
        formCues: ['Core tight', 'Don\'t flare elbows', 'Full extension'],
        commonMistakes: ['Arching back', 'Partial reps'],
        icon: '🏋️',
    },
    'Arnold Press': {
        name: 'Arnold Press',
        muscles: ['All Heads of Deltoids'],
        equipment: 'Dumbbells',
        difficulty: 'intermediate',
        instructions: ['Start with palms facing you at shoulders', 'Rotate palms out as you press', 'Full lockout overhead', 'Reverse motion down'],
        formCues: ['Smooth rotation', 'Full range', 'Control throughout'],
        commonMistakes: ['Rushing the rotation', 'Limited range'],
        icon: '💪',
    },
    'Lateral Raise': {
        name: 'Lateral Raise',
        muscles: ['Side Delts'],
        equipment: 'Dumbbells',
        difficulty: 'beginner',
        instructions: ['Stand with dumbbells at sides', 'Slight bend in elbows', 'Raise arms out to sides until parallel', 'Lower with control'],
        formCues: ['Lead with elbows', 'Pinky up at top', 'Controlled tempo'],
        commonMistakes: ['Using momentum', 'Going too heavy', 'Shrugging shoulders'],
        icon: '🦅',
    },
    'Front Raise': {
        name: 'Front Raise',
        muscles: ['Front Delts'],
        equipment: 'Dumbbells or Plate',
        difficulty: 'beginner',
        instructions: ['Stand with weight at thighs', 'Raise arms forward to shoulder height', 'Lower with control', 'Alternate or together'],
        formCues: ['No momentum', 'Stop at shoulder height', 'Control descent'],
        commonMistakes: ['Swinging weight', 'Going too high'],
        icon: '🙋',
    },
    'Rear Delt Fly': {
        name: 'Rear Delt Fly',
        muscles: ['Rear Delts', 'Upper Back'],
        equipment: 'Dumbbells or Machine',
        difficulty: 'beginner',
        instructions: ['Bend over or use machine', 'Arms hanging or at start position', 'Raise out to sides', 'Squeeze rear delts'],
        formCues: ['Lead with elbows', 'Pinch shoulder blades', 'Control the weight'],
        commonMistakes: ['Using too much momentum', 'Not squeezing'],
        icon: '🦋',
    },
    'Upright Row': {
        name: 'Upright Row',
        muscles: ['Side Delts', 'Traps'],
        equipment: 'Barbell or Dumbbells',
        difficulty: 'intermediate',
        instructions: ['Hold weight at thighs', 'Pull up along body', 'Elbows lead, go to chin level', 'Lower with control'],
        formCues: ['Lead with elbows', 'Keep close to body', 'Don\'t go too high'],
        commonMistakes: ['Going too high (impingement)', 'Grip too narrow'],
        icon: '⬆️',
    },
    'Shrugs': {
        name: 'Shrugs',
        muscles: ['Traps'],
        equipment: 'Barbell or Dumbbells',
        difficulty: 'beginner',
        instructions: ['Hold weight at sides or front', 'Shrug shoulders straight up', 'Squeeze at top', 'Lower with control'],
        formCues: ['Straight up, not rolling', 'Hold at top', 'Heavy weight okay'],
        commonMistakes: ['Rolling shoulders', 'Not pausing at top'],
        icon: '🤷',
    },

    // ============ ARMS ============
    'Barbell Curl': {
        name: 'Barbell Curl',
        muscles: ['Biceps', 'Forearms'],
        equipment: 'Barbell',
        difficulty: 'beginner',
        instructions: ['Stand with bar at arm\'s length', 'Keep elbows pinned to sides', 'Curl weight up with control', 'Squeeze biceps at top', 'Lower slowly'],
        formCues: ['No swinging', 'Elbows stay still', 'Full contraction at top'],
        commonMistakes: ['Swinging body', 'Moving elbows forward', 'Partial reps'],
        icon: '💪',
    },
    'Dumbbell Curl': {
        name: 'Dumbbell Curl',
        muscles: ['Biceps', 'Forearms'],
        equipment: 'Dumbbells',
        difficulty: 'beginner',
        instructions: ['Stand or sit with DBs at sides', 'Curl up with supinated grip', 'Squeeze at top', 'Lower with control'],
        formCues: ['Full supination', 'No momentum', 'Equal reps each side'],
        commonMistakes: ['Swinging', 'Alternating too fast'],
        icon: '💪',
    },
    'Hammer Curl': {
        name: 'Hammer Curl',
        muscles: ['Biceps', 'Brachialis', 'Forearms'],
        equipment: 'Dumbbells',
        difficulty: 'beginner',
        instructions: ['Neutral grip (palms facing in)', 'Curl up keeping neutral position', 'Squeeze at top', 'Lower with control'],
        formCues: ['Keep neutral grip', 'Elbows stay pinned', 'Full range'],
        commonMistakes: ['Rotating grip', 'Swinging'],
        icon: '🔨',
    },
    'Preacher Curl': {
        name: 'Preacher Curl',
        muscles: ['Biceps'],
        equipment: 'EZ Bar, Preacher Bench',
        difficulty: 'beginner',
        instructions: ['Arms over preacher pad', 'Curl up from full extension', 'Squeeze at top', 'Lower with control'],
        formCues: ['Full stretch at bottom', 'Don\'t come up too high', 'Control negative'],
        commonMistakes: ['Cutting range short', 'Lifting elbows off pad'],
        icon: '📖',
    },
    'Concentration Curl': {
        name: 'Concentration Curl',
        muscles: ['Biceps'],
        equipment: 'Dumbbell',
        difficulty: 'beginner',
        instructions: ['Sit, elbow on inner thigh', 'Curl dumbbell up', 'Squeeze hard at top', 'Lower slowly'],
        formCues: ['Elbow stays still', 'Full concentration', 'Squeeze peak'],
        commonMistakes: ['Moving elbow', 'Using momentum'],
        icon: '🧠',
    },
    'Cable Curl': {
        name: 'Cable Curl',
        muscles: ['Biceps'],
        equipment: 'Cable Machine',
        difficulty: 'beginner',
        instructions: ['Stand facing low cable', 'Curl handle up', 'Squeeze at top', 'Return with control'],
        formCues: ['Constant tension', 'Elbows pinned', 'Control both directions'],
        commonMistakes: ['Leaning back', 'Too fast'],
        icon: '🔗',
    },
    'Tricep Pushdown': {
        name: 'Tricep Pushdown',
        muscles: ['Triceps'],
        equipment: 'Cable Machine',
        difficulty: 'beginner',
        instructions: ['Stand facing cable, grip attachment', 'Pin elbows to sides', 'Push down to full extension', 'Squeeze triceps, return slowly'],
        formCues: ['Only forearms move', 'Full lockout', 'Control the negative'],
        commonMistakes: ['Leaning over weight', 'Elbows drifting', 'Using momentum'],
        icon: '⬇️',
    },
    'Skull Crushers': {
        name: 'Skull Crushers',
        muscles: ['Triceps'],
        equipment: 'EZ Bar or Dumbbells, Bench',
        difficulty: 'intermediate',
        instructions: ['Lie on bench with arms extended', 'Lower weight toward forehead', 'Keep upper arms vertical', 'Extend back up'],
        formCues: ['Elbows stay in', 'Control the descent', 'Full extension'],
        commonMistakes: ['Elbows flaring', 'Weight moving too fast', 'Upper arms moving'],
        icon: '💀',
    },
    'Overhead Tricep Extension': {
        name: 'Overhead Tricep Extension',
        muscles: ['Triceps (Long Head)'],
        equipment: 'Dumbbell or Cable',
        difficulty: 'beginner',
        instructions: ['Hold weight overhead', 'Lower behind head by bending elbows', 'Keep upper arms still', 'Extend back up'],
        formCues: ['Elbows point up', 'Full stretch at bottom', 'Lock out at top'],
        commonMistakes: ['Elbows flaring', 'Moving upper arms'],
        icon: '🙋',
    },
    'Tricep Dips': {
        name: 'Tricep Dips',
        muscles: ['Triceps', 'Chest', 'Front Delts'],
        equipment: 'Dip Bars or Bench',
        difficulty: 'intermediate',
        instructions: ['Grip bars, body upright', 'Lower until upper arms parallel', 'Press back up', 'Full lockout'],
        formCues: ['Stay upright for triceps', 'Don\'t go too deep', 'Lock out top'],
        commonMistakes: ['Leaning too forward', 'Going too deep'],
        icon: '⬇️',
    },
    'Close Grip Bench Press': {
        name: 'Close Grip Bench Press',
        muscles: ['Triceps', 'Chest'],
        equipment: 'Barbell, Bench',
        difficulty: 'intermediate',
        instructions: ['Grip bar shoulder-width or narrower', 'Lower to lower chest', 'Keep elbows tucked', 'Press up'],
        formCues: ['Elbows at 45 degrees', 'Touch lower chest', 'Tricep focus'],
        commonMistakes: ['Grip too narrow', 'Elbows flaring'],
        icon: '🏋️',
    },

    // ============ LEGS ============
    'Squat': {
        name: 'Squat',
        muscles: ['Quads', 'Glutes', 'Hamstrings', 'Core'],
        equipment: 'Barbell, Squat Rack',
        difficulty: 'intermediate',
        instructions: ['Bar on upper back, feet shoulder-width', 'Brace core, take a deep breath', 'Sit back and down, knees track over toes', 'Descend until hip crease below knee', 'Drive up through heels'],
        formCues: ['Knees out', 'Chest up', 'Drive hips forward at top', 'Full depth'],
        commonMistakes: ['Knees caving in', 'Leaning too forward', 'Cutting depth short'],
        icon: '🦵',
        imageKey: 'squat',
    },
    'Back Squat': {
        name: 'Back Squat',
        muscles: ['Quads', 'Glutes', 'Hamstrings', 'Core'],
        equipment: 'Barbell, Squat Rack',
        difficulty: 'intermediate',
        instructions: ['Bar on upper back', 'Feet shoulder-width', 'Squat to depth', 'Drive up'],
        formCues: ['Brace hard', 'Knees out', 'Full depth'],
        commonMistakes: ['Knees caving', 'Forward lean', 'Shallow depth'],
        icon: '🦵',
    },
    'Front Squat': {
        name: 'Front Squat',
        muscles: ['Quads', 'Core', 'Upper Back'],
        equipment: 'Barbell, Squat Rack',
        difficulty: 'advanced',
        instructions: ['Bar in front rack position', 'Elbows high, chest up', 'Squat deep, stay upright', 'Drive up'],
        formCues: ['Elbows up throughout', 'Stay very upright', 'Core braced hard'],
        commonMistakes: ['Elbows dropping', 'Forward lean', 'Wrist pain'],
        icon: '🎯',
    },
    'Goblet Squat': {
        name: 'Goblet Squat',
        muscles: ['Quads', 'Glutes', 'Core'],
        equipment: 'Dumbbell or Kettlebell',
        difficulty: 'beginner',
        instructions: ['Hold weight at chest', 'Squat between legs', 'Keep chest up', 'Drive up'],
        formCues: ['Elbows inside knees', 'Chest proud', 'Full depth'],
        commonMistakes: ['Leaning forward', 'Heels rising'],
        icon: '🏆',
    },
    'Leg Press': {
        name: 'Leg Press',
        muscles: ['Quads', 'Glutes', 'Hamstrings'],
        equipment: 'Leg Press Machine',
        difficulty: 'beginner',
        instructions: ['Sit with back flat against pad', 'Feet shoulder-width on platform', 'Lower weight with control', 'Press back up without locking knees'],
        formCues: ['Keep lower back on pad', 'Control the negative', 'Breathe at top'],
        commonMistakes: ['Locking knees', 'Lower back lifting', 'Too narrow stance'],
        icon: '🦿',
    },
    'Hack Squat': {
        name: 'Hack Squat',
        muscles: ['Quads', 'Glutes'],
        equipment: 'Hack Squat Machine',
        difficulty: 'beginner',
        instructions: ['Shoulders under pads', 'Feet forward on platform', 'Squat down', 'Drive up'],
        formCues: ['Back against pad', 'Control descent', 'Full depth'],
        commonMistakes: ['Coming forward', 'Partial reps'],
        icon: '🔧',
    },
    'Bulgarian Split Squat': {
        name: 'Bulgarian Split Squat',
        muscles: ['Quads', 'Glutes', 'Hamstrings'],
        equipment: 'Bench, Dumbbells optional',
        difficulty: 'intermediate',
        instructions: ['Rear foot on bench', 'Lower until front thigh parallel', 'Drive through front heel', 'Keep torso upright'],
        formCues: ['Front knee tracks over toes', 'Stay upright', 'Control the descent'],
        commonMistakes: ['Leaning forward', 'Knee caving'],
        icon: '🇧🇬',
    },
    'Lunges': {
        name: 'Lunges',
        muscles: ['Quads', 'Glutes', 'Hamstrings'],
        equipment: 'Bodyweight or Dumbbells',
        difficulty: 'beginner',
        instructions: ['Stand tall, step forward', 'Lower until both knees at 90 degrees', 'Push through front heel to return', 'Alternate legs'],
        formCues: ['Torso upright', 'Knee over ankle', 'Control the step'],
        commonMistakes: ['Knee past toes', 'Leaning forward', 'Short steps'],
        icon: '🚶',
    },
    'Walking Lunges': {
        name: 'Walking Lunges',
        muscles: ['Quads', 'Glutes', 'Hamstrings'],
        equipment: 'Bodyweight or Dumbbells',
        difficulty: 'beginner',
        instructions: ['Step forward into lunge', 'Drive through and step into next lunge', 'Keep moving forward', 'Alternating legs'],
        formCues: ['Stay upright', 'Big steps', 'Control balance'],
        commonMistakes: ['Rushing', 'Short steps', 'Poor balance'],
        icon: '🚶',
    },
    'Leg Extension': {
        name: 'Leg Extension',
        muscles: ['Quads'],
        equipment: 'Leg Extension Machine',
        difficulty: 'beginner',
        instructions: ['Sit with back against pad', 'Ankles behind roller', 'Extend legs fully', 'Lower with control'],
        formCues: ['Full extension', 'Squeeze at top', 'Don\'t swing'],
        commonMistakes: ['Using momentum', 'Partial reps'],
        icon: '🦵',
    },
    'Leg Curl': {
        name: 'Leg Curl',
        muscles: ['Hamstrings'],
        equipment: 'Leg Curl Machine',
        difficulty: 'beginner',
        instructions: ['Lie face down', 'Ankles under roller', 'Curl heels to glutes', 'Lower with control'],
        formCues: ['Squeeze at top', 'Control the negative', 'Hips stay down'],
        commonMistakes: ['Hips rising', 'Using momentum'],
        icon: '🔄',
    },
    'Romanian Deadlift': {
        name: 'Romanian Deadlift',
        muscles: ['Hamstrings', 'Glutes', 'Lower Back'],
        equipment: 'Barbell or Dumbbells',
        difficulty: 'intermediate',
        instructions: ['Stand with bar at hips, slight knee bend', 'Push hips back while lowering bar', 'Keep bar close to legs', 'Feel stretch in hamstrings', 'Drive hips forward to stand'],
        formCues: ['Hips back, not down', 'Flat back always', 'Squeeze glutes at top'],
        commonMistakes: ['Rounding back', 'Bending knees too much', 'Bar drifting forward'],
        icon: '🍑',
    },
    'Stiff Leg Deadlift': {
        name: 'Stiff Leg Deadlift',
        muscles: ['Hamstrings', 'Glutes', 'Lower Back'],
        equipment: 'Barbell',
        difficulty: 'intermediate',
        instructions: ['Minimal knee bend', 'Hinge forward keeping legs straight', 'Lower bar to mid-shin or floor', 'Stand back up'],
        formCues: ['Legs stay stiff', 'Hips back', 'Flat back'],
        commonMistakes: ['Bending knees too much', 'Rounding back'],
        icon: '🦵',
    },
    'Hip Thrust': {
        name: 'Hip Thrust',
        muscles: ['Glutes', 'Hamstrings'],
        equipment: 'Barbell, Bench',
        difficulty: 'intermediate',
        instructions: ['Upper back on bench', 'Bar over hips', 'Drive hips up, squeezing glutes', 'Lower with control'],
        formCues: ['Chin tucked', 'Full hip extension', 'Squeeze glutes hard'],
        commonMistakes: ['Hyperextending back', 'Not full extension'],
        icon: '🍑',
    },
    'Glute Bridge': {
        name: 'Glute Bridge',
        muscles: ['Glutes', 'Hamstrings'],
        equipment: 'Bodyweight or Barbell',
        difficulty: 'beginner',
        instructions: ['Lie on back, feet flat', 'Drive hips up', 'Squeeze glutes at top', 'Lower with control'],
        formCues: ['Drive through heels', 'Squeeze at top', 'Control descent'],
        commonMistakes: ['Using lower back', 'Not squeezing glutes'],
        icon: '🌉',
    },
    'Calf Raise': {
        name: 'Calf Raise',
        muscles: ['Calves'],
        equipment: 'Machine or Bodyweight',
        difficulty: 'beginner',
        instructions: ['Stand on edge of platform', 'Lower heels below platform', 'Rise up on toes', 'Squeeze at top'],
        formCues: ['Full range of motion', 'Hold at top', 'Control descent'],
        commonMistakes: ['Bouncing', 'Partial reps'],
        icon: '🦶',
    },
    'Seated Calf Raise': {
        name: 'Seated Calf Raise',
        muscles: ['Soleus', 'Calves'],
        equipment: 'Seated Calf Machine',
        difficulty: 'beginner',
        instructions: ['Sit with pads on thighs', 'Lower heels down', 'Press up on toes', 'Squeeze at top'],
        formCues: ['Bent knee position', 'Full stretch', 'Hold contraction'],
        commonMistakes: ['Too fast', 'Limited range'],
        icon: '🦶',
    },

    // ============ CORE ============
    'Plank': {
        name: 'Plank',
        muscles: ['Core', 'Shoulders'],
        equipment: 'Bodyweight',
        difficulty: 'beginner',
        instructions: ['Forearms and toes on ground', 'Body in straight line', 'Brace core tight', 'Hold position'],
        formCues: ['Squeeze glutes', 'Don\'t let hips sag', 'Breathe steadily'],
        commonMistakes: ['Hips too high/low', 'Not engaging core'],
        icon: '📏',
    },
    'Crunches': {
        name: 'Crunches',
        muscles: ['Abs'],
        equipment: 'Bodyweight',
        difficulty: 'beginner',
        instructions: ['Lie on back, knees bent', 'Hands behind head or across chest', 'Curl shoulders up', 'Lower with control'],
        formCues: ['Don\'t pull on neck', 'Exhale on crunch', 'Focus on contraction'],
        commonMistakes: ['Pulling neck', 'Using momentum'],
        icon: '🥨',
    },
    'Leg Raises': {
        name: 'Leg Raises',
        muscles: ['Lower Abs', 'Hip Flexors'],
        equipment: 'Bodyweight',
        difficulty: 'intermediate',
        instructions: ['Lie flat, legs extended', 'Keep lower back pressed down', 'Raise legs to 90 degrees', 'Lower with control'],
        formCues: ['Control the descent', 'Lower back stays down', 'Don\'t swing'],
        commonMistakes: ['Lower back arching', 'Swinging legs'],
        icon: '🦵',
    },
    'Hanging Leg Raises': {
        name: 'Hanging Leg Raises',
        muscles: ['Lower Abs', 'Hip Flexors'],
        equipment: 'Pull-up Bar',
        difficulty: 'advanced',
        instructions: ['Hang from bar', 'Raise legs to parallel or higher', 'Lower with control', 'Minimize swing'],
        formCues: ['Control the swing', 'Curl pelvis up', 'Full range'],
        commonMistakes: ['Too much swinging', 'Just hip flexion'],
        icon: '🤸',
    },
    'Russian Twists': {
        name: 'Russian Twists',
        muscles: ['Obliques', 'Abs'],
        equipment: 'Bodyweight or Weight',
        difficulty: 'beginner',
        instructions: ['Sit with feet off ground', 'Lean back slightly', 'Rotate torso side to side', 'Touch ground each side'],
        formCues: ['Keep chest up', 'Control rotation', 'Exhale on twist'],
        commonMistakes: ['Just moving arms', 'Too fast'],
        icon: '🔄',
    },
    'Ab Wheel Rollout': {
        name: 'Ab Wheel Rollout',
        muscles: ['Abs', 'Lats', 'Shoulders'],
        equipment: 'Ab Wheel',
        difficulty: 'advanced',
        instructions: ['Kneel with wheel in front', 'Roll forward extending body', 'Keep core tight', 'Roll back to start'],
        formCues: ['Don\'t let hips sag', 'Squeeze abs throughout', 'Control the movement'],
        commonMistakes: ['Hips dropping', 'Not going full range'],
        icon: '🎡',
    },
    'Cable Woodchops': {
        name: 'Cable Woodchops',
        muscles: ['Obliques', 'Core', 'Shoulders'],
        equipment: 'Cable Machine',
        difficulty: 'intermediate',
        instructions: ['Set cable high or low', 'Rotate diagonally across body', 'Control the movement', 'Rotate at hips and core'],
        formCues: ['Keep arms straight', 'Rotate through hips', 'Control both directions'],
        commonMistakes: ['Just using arms', 'Too fast'],
        icon: '🪓',
    },
    'Dead Bug': {
        name: 'Dead Bug',
        muscles: ['Core', 'Hip Flexors'],
        equipment: 'Bodyweight',
        difficulty: 'beginner',
        instructions: ['Lie on back, arms up, knees at 90', 'Extend opposite arm and leg', 'Keep lower back pressed down', 'Return and alternate'],
        formCues: ['Lower back stays flat', 'Controlled movement', 'Breathe steadily'],
        commonMistakes: ['Back arching', 'Moving too fast'],
        icon: '🐛',
    },
};

// Get exercise info with fallback for unknown exercises
export function getExerciseInfo(exerciseName: string): ExerciseInfo | null {
    // Try exact match
    if (EXERCISE_DATABASE[exerciseName]) {
        return EXERCISE_DATABASE[exerciseName];
    }

    // Try case-insensitive match
    const lowerName = exerciseName.toLowerCase();
    for (const [name, info] of Object.entries(EXERCISE_DATABASE)) {
        if (name.toLowerCase() === lowerName) {
            return info;
        }
    }

    // Try partial match
    for (const [name, info] of Object.entries(EXERCISE_DATABASE)) {
        if (lowerName.includes(name.toLowerCase()) || name.toLowerCase().includes(lowerName)) {
            return info;
        }
    }

    return null; // Unknown exercise
}
